version: '3.8'
services:
  gateway:
    build: gateway
    image: gateway-image
    container_name: shareit-gateway
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090
      - TZ=Europe/Moscow

  server:
    build: server
    image: server-image
    container_name: shareit-server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - POSTGRES_DB=shareIt
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB_HOST=db
      - POSTGRES_DB_PORT=5432

  db:
    image: postgres:16-alpine
    container_name: shareit-db
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=shareIt
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10