services:
  gateway:
    build: gateway
    image: gateway-image
    container_name: gateway
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://localhost:9090

  server:
    build: server
    image: server-image
    container_name: server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - POSTGRES_DB=shareIt
        - POSTGRES_USER=dbuser
        - POSTGRES_PASSWORD=12345
        - POSTGRES_DB_HOST=db
        - POSTGRES_DB_PORT=5432

  db:
  image: postgres:16.1
  container_name: db
  ports:
    - "5432:5432"
  volumes:
    - ./volumes/postgres:/var/lib/postgresql/data/
  environment:
    - POSTGRES_DB=shareIt
    - POSTGRES_USER=dbuser
    - POSTGRES_PASSWORD=12345
  healthcheck:
    test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
    timeout: 5s
    interval: 5s
    retries: 10